version: '3.8'
services:
    db:
      image: market-database
      build:
        context: .
        dockerfile: Dockerfile
        target: development
      container_name: supermarket_db
      restart: always
      environment:
        POSTGRES_DB: market_db
        POSTGRES_USER: market_db_admin
        POSTGRES_PASSWORD: admin
      ports:
        - '8181:5432'
      volumes:
        - /db:/var/lib/postgresql/data/


