insert into category (name, description, created_date) values ('Hand Towel', 'Other vomiting complicating pregnancy', '08-29-2022');
insert into category (name, description, created_date) values ('Trout - Hot Smkd, Dbl Fillet', 'Displaced fracture of distal phalanx of right index finger', '08-29-2022');
insert into category (name, description, created_date) values ('Tahini Paste', 'Cracked nipple associated with pregnancy, third trimester', '08-29-2022');
insert into category (name, description, created_date) values ('Shrimp - Baby, Cold Water', 'Oth place in oth residential institution as place', '08-29-2022');
insert into category (name, description, created_date) values ('Sage - Ground', 'Other myositis, left ankle and foot', '08-29-2022');
insert into category (name, description, created_date) values ('Pepper - Chilli Seeds Mild', 'Segmental and somatic dysfunction of abdomen and oth regions', '08-29-2022');
insert into category (name, description, created_date) values ('Broom And Broom Rack White', 'Incomplete atypical femoral fracture, right leg, init', '08-29-2022');
insert into category (name, description, created_date) values ('Mcguinness - Blue Curacao', 'Displaced other extraarticular fracture of unsp calcaneus', '08-29-2022');
insert into category (name, description, created_date) values ('Tuna - Bluefin', 'Breakdown of prosthetic orbit of right eye, init', '08-29-2022');
insert into category (name, description, created_date) values ('Sobe - Lizard Fuel', 'External constriction of right ear, initial encounter', '08-29-2022');
insert into category (name, description, created_date) values ('Sobe - Liz Blizz', 'Other contact with cow', '08-29-2022');
insert into category (name, description, created_date) values ('Dates', 'Other hypertrophic osteoarthropathy, unspecified forearm', '08-29-2022');
insert into category (name, description, created_date) values ('Champagne - Brights, Dry', 'Disp fx of unsp ulna styloid pro, 7thG', '08-29-2022');
insert into category (name, description, created_date) values ('Mushroom - Lg - Cello', 'Typhoid arthritis', '08-29-2022');
insert into category (name, description, created_date) values ('Lettuce - Frisee', 'Unsp inj extn musc/fasc/tend finger at wrs/hnd lv, sequela', '08-29-2022');
insert into category (name, description, created_date) values ('Muffin Puck Ww Carrot', 'Walked into lamppost, subsequent encounter', '08-29-2022');
insert into category (name, description, created_date) values ('Veal - Round, Eye Of', 'Nondisp spiral fx shaft of unsp fibula, 7thM', '08-29-2022');
insert into category (name, description, created_date) values ('Table Cloth 72x144 White', 'Disp fx of nk of l rad, 7thR', '08-29-2022');
insert into category (name, description, created_date) values ('Chicken Giblets', 'Burn of first deg mult sites of unsp wrist and hand', '08-29-2022');
insert into category (name, description, created_date) values ('Container - Clear 16 Oz', 'Inj unsp muscles, fascia and tendons at forearm level', '08-29-2022');
