insert into category (name, description) values ('Hand Towel', 'Other vomiting complicating pregnancy');
insert into category (name, description) values ('Trout - Hot Smkd, Dbl Fillet', 'Displaced fracture of distal phalanx of right index finger');
insert into category (name, description) values ('Tahini Paste', 'Cracked nipple associated with pregnancy, third trimester');
insert into category (name, description) values ('Shrimp - Baby, Cold Water', 'Oth place in oth residential institution as place');
insert into category (name, description) values ('Sage - Ground', 'Other myositis, left ankle and foot');
insert into category (name, description) values ('Pepper - Chilli Seeds Mild', 'Segmental and somatic dysfunction of abdomen and oth regions');
insert into category (name, description) values ('Broom And Broom Rack White', 'Incomplete atypical femoral fracture, right leg, init');
insert into category (name, description) values ('Mcguinness - Blue Curacao', 'Displaced other extraarticular fracture of unsp calcaneus');
insert into category (name, description) values ('Tuna - Bluefin', 'Breakdown of prosthetic orbit of right eye, init');
insert into category (name, description) values ('Sobe - Lizard Fuel', 'External constriction of right ear, initial encounter');
insert into category (name, description) values ('Sobe - Liz Blizz', 'Other contact with cow');
insert into category (name, description) values ('Dates', 'Other hypertrophic osteoarthropathy, unspecified forearm');
insert into category (name, description) values ('Champagne - Brights, Dry', 'Disp fx of unsp ulna styloid pro, 7thG');
insert into category (name, description) values ('Mushroom - Lg - Cello', 'Typhoid arthritis');
insert into category (name, description) values ('Lettuce - Frisee', 'Unsp inj extn musc/fasc/tend finger at wrs/hnd lv, sequela');
insert into category (name, description) values ('Muffin Puck Ww Carrot', 'Walked into lamppost, subsequent encounter');
insert into category (name, description) values ('Veal - Round, Eye Of', 'Nondisp spiral fx shaft of unsp fibula, 7thM');
insert into category (name, description) values ('Table Cloth 72x144 White', 'Disp fx of nk of l rad, 7thR');
insert into category (name, description) values ('Chicken Giblets', 'Burn of first deg mult sites of unsp wrist and hand');
insert into category (name, description) values ('Container - Clear 16 Oz', 'Inj unsp muscles, fascia and tendons at forearm level');
