insert into product (name, unit_price, category_id) values ('Wine - Conde De Valdemar', 186.11, 2);
insert into product (name, unit_price, category_id) values ('Onions Granulated', 120.67, 14);
insert into product (name, unit_price, category_id) values ('Oneshot Automatic Soap System', 165.13, 14);
insert into product (name, unit_price, category_id) values ('Icecream Cone - Areo Chocolate', 122.02, 7);
insert into product (name, unit_price, category_id) values ('Watercress', 90.23, 9);
insert into product (name, unit_price, category_id) values ('Appetizer - Mushroom Tart', 151.59, 3);
insert into product (name, unit_price, category_id) values ('Water - Mineral, Natural', 14.54, 5);
insert into product (name, unit_price, category_id) values ('Ham Black Forest', 134.65, 11);
insert into product (name, unit_price, category_id) values ('Easy Off Oven Cleaner', 98.01, 3);
insert into product (name, unit_price, category_id) values ('Water - Aquafina Vitamin', 104.08, 5);
insert into product (name, unit_price, category_id) values ('Halibut - Steaks', 128.43, 19);
insert into product (name, unit_price, category_id) values ('Wine - Sogrape Mateus Rose', 129.84, 6);
insert into product (name, unit_price, category_id) values ('Coconut - Shredded, Unsweet', 123.91, 2);
insert into product (name, unit_price, category_id) values ('Sauerkraut', 107.09, 5);
insert into product (name, unit_price, category_id) values ('Tea - Earl Grey', 111.9, 2);
insert into product (name, unit_price, category_id) values ('Cookie - Dough Variety', 122.7, 11);
insert into product (name, unit_price, category_id) values ('Wine - Vineland Estate Semi - Dry', 70.8, 2);
insert into product (name, unit_price, category_id) values ('Pepper - Paprika, Hungarian', 145.48, 16);
insert into product (name, unit_price, category_id) values ('Cheese - Brie Roitelet', 121.32, 20);
insert into product (name, unit_price, category_id) values ('Mushroom - Morel Frozen', 35.22, 1);
insert into product (name, unit_price, category_id) values ('Wine - Cabernet Sauvignon', 193.97, 20);
insert into product (name, unit_price, category_id) values ('Fudge - Cream Fudge', 126.48, 1);
insert into product (name, unit_price, category_id) values ('Oil - Canola', 102.37, 12);
insert into product (name, unit_price, category_id) values ('Vinegar - Balsamic', 111.16, 3);
insert into product (name, unit_price, category_id) values ('Napkin - Beverage 1 Ply', 196.61, 5);
insert into product (name, unit_price, category_id) values ('Puree - Mocha', 178.61, 12);
insert into product (name, unit_price, category_id) values ('Sprouts - Pea', 128.48, 3);
insert into product (name, unit_price, category_id) values ('Ice Cream Bar - Rolo Cone', 50.05, 19);
insert into product (name, unit_price, category_id) values ('Tart - Lemon', 174.35, 1);
insert into product (name, unit_price, category_id) values ('Mushroom - Porcini, Dry', 162.12, 20);
insert into product (name, unit_price, category_id) values ('Molasses - Fancy', 107.46, 5);
insert into product (name, unit_price, category_id) values ('Pork - Bacon, Sliced', 133.75, 10);
insert into product (name, unit_price, category_id) values ('Bread - Hot Dog Buns', 72.87, 7);
insert into product (name, unit_price, category_id) values ('Energy Drink - Redbull 355ml', 45.4, 17);
insert into product (name, unit_price, category_id) values ('Sprouts - Alfalfa', 134.89, 4);
insert into product (name, unit_price, category_id) values ('Pepper - Pablano', 40.88, 20);
insert into product (name, unit_price, category_id) values ('Beer - Original Organic Lager', 52.71, 2);
insert into product (name, unit_price, category_id) values ('Milk Powder', 41.46, 15);
insert into product (name, unit_price, category_id) values ('Chocolate - Pistoles, Lactee, Milk', 113.68, 11);
insert into product (name, unit_price, category_id) values ('Cookie Choc', 121.13, 19);
insert into product (name, unit_price, category_id) values ('Wine - Muscadet Sur Lie', 63.32, 15);
insert into product (name, unit_price, category_id) values ('Beer - Corona', 15.95, 19);
insert into product (name, unit_price, category_id) values ('Bread - Frozen Basket Variety', 64.3, 17);
insert into product (name, unit_price, category_id) values ('Peas - Frozen', 21.85, 14);
insert into product (name, unit_price, category_id) values ('Crackers - Soda / Saltins', 94.98, 11);
insert into product (name, unit_price, category_id) values ('Juice - Pineapple, 341 Ml', 64.7, 3);
insert into product (name, unit_price, category_id) values ('Juice - Cranberry, 341 Ml', 72.91, 13);
insert into product (name, unit_price, category_id) values ('Beef - Striploin', 138.17, 9);
insert into product (name, unit_price, category_id) values ('Beef - Montreal Smoked Brisket', 69.23, 11);
insert into product (name, unit_price, category_id) values ('Squash - Sunburst', 63.91, 12);
insert into product (name, unit_price, category_id) values ('Beef - Tender Tips', 159.0, 15);
insert into product (name, unit_price, category_id) values ('Puree - Guava', 115.57, 9);
insert into product (name, unit_price, category_id) values ('Wine - White, Concha Y Toro', 170.44, 11);
insert into product (name, unit_price, category_id) values ('Pepper - Green, Chili', 36.51, 16);
insert into product (name, unit_price, category_id) values ('Greens Mustard', 34.78, 8);
insert into product (name, unit_price, category_id) values ('Nut - Pecan, Halves', 163.11, 11);
insert into product (name, unit_price, category_id) values ('Apricots - Dried', 139.6, 20);
insert into product (name, unit_price, category_id) values ('Juice - Apple Cider', 85.12, 5);
insert into product (name, unit_price, category_id) values ('Radish', 194.45, 9);
insert into product (name, unit_price, category_id) values ('Coffee Beans - Chocolate', 175.97, 20);
insert into product (name, unit_price, category_id) values ('Pie Pecan', 51.64, 15);
insert into product (name, unit_price, category_id) values ('Pepper - Red Chili', 24.2, 1);
insert into product (name, unit_price, category_id) values ('Coffee Swiss Choc Almond', 85.07, 12);
insert into product (name, unit_price, category_id) values ('Eggplant Italian', 195.32, 17);
insert into product (name, unit_price, category_id) values ('Jolt Cola', 86.84, 16);
insert into product (name, unit_price, category_id) values ('Yeast Dry - Fermipan', 128.04, 5);
insert into product (name, unit_price, category_id) values ('Rum - Light, Captain Morgan', 21.26, 16);
insert into product (name, unit_price, category_id) values ('Calypso - Lemonade', 52.4, 13);
insert into product (name, unit_price, category_id) values ('Carbonated Water - Strawberry', 122.94, 18);
insert into product (name, unit_price, category_id) values ('Pasta - Lasagna Noodle, Frozen', 197.38, 17);
insert into product (name, unit_price, category_id) values ('Muffin Mix - Carrot', 116.99, 5);
insert into product (name, unit_price, category_id) values ('Bread - Bagels, Plain', 100.43, 2);
insert into product (name, unit_price, category_id) values ('Pineapple - Golden', 12.41, 4);
insert into product (name, unit_price, category_id) values ('Lamb - Ground', 192.49, 19);
insert into product (name, unit_price, category_id) values ('Veal - Nuckle', 105.5, 20);
insert into product (name, unit_price, category_id) values ('Banana', 19.22, 7);
insert into product (name, unit_price, category_id) values ('Ostrich - Prime Cut', 167.8, 4);
insert into product (name, unit_price, category_id) values ('Butter Balls Salted', 84.83, 6);
insert into product (name, unit_price, category_id) values ('Wine - Spumante Bambino White', 199.94, 3);
insert into product (name, unit_price, category_id) values ('Miso Paste White', 131.42, 2);
insert into product (name, unit_price, category_id) values ('Salt And Pepper Mix - Black', 51.47, 15);
insert into product (name, unit_price, category_id) values ('Extract Vanilla Pure', 136.87, 4);
insert into product (name, unit_price, category_id) values ('Ostrich - Fan Fillet', 198.16, 3);
insert into product (name, unit_price, category_id) values ('Flour - All Purpose', 36.37, 12);
insert into product (name, unit_price, category_id) values ('Sugar - Cubes', 194.33, 9);
insert into product (name, unit_price, category_id) values ('Bread - Bagels, Mini', 97.65, 4);
insert into product (name, unit_price, category_id) values ('Flour - Cake', 25.21, 15);
insert into product (name, unit_price, category_id) values ('Pasta - Ravioli', 109.28, 17);
insert into product (name, unit_price, category_id) values ('Chips - Miss Vickies', 134.5, 1);
insert into product (name, unit_price, category_id) values ('Chinese Foods - Chicken', 38.88, 2);
insert into product (name, unit_price, category_id) values ('Cheese - Sheep Milk', 173.68, 11);
insert into product (name, unit_price, category_id) values ('Trueblue - Blueberry', 64.65, 1);
insert into product (name, unit_price, category_id) values ('Cake - Pancake', 179.33, 20);
insert into product (name, unit_price, category_id) values ('Bread - Italian Roll With Herbs', 98.34, 8);
insert into product (name, unit_price, category_id) values ('Wine - Chardonnay Mondavi', 146.59, 20);
insert into product (name, unit_price, category_id) values ('Salmon Steak - Cohoe 8 Oz', 93.15, 18);
insert into product (name, unit_price, category_id) values ('Bread - Flat Bread', 138.51, 4);
insert into product (name, unit_price, category_id) values ('Sugar - Cubes', 155.76, 2);
insert into product (name, unit_price, category_id) values ('Garlic - Primerba, Paste', 26.43, 10);
insert into product (name, unit_price, category_id) values ('Lid - Translucent, 3.5 And 6 Oz', 142.83, 20);
insert into product (name, unit_price, category_id) values ('Wine - Sauvignon Blanc', 28.34, 17);
insert into product (name, unit_price, category_id) values ('Muffin Batt - Ban Dream Zero', 132.9, 3);
insert into product (name, unit_price, category_id) values ('Juice - Ocean Spray Cranberry', 177.98, 2);
insert into product (name, unit_price, category_id) values ('Dr. Pepper - 355ml', 146.0, 10);
insert into product (name, unit_price, category_id) values ('Wine - Magnotta - Cab Franc', 97.79, 20);
insert into product (name, unit_price, category_id) values ('Pasta - Penne, Lisce, Dry', 16.76, 15);
insert into product (name, unit_price, category_id) values ('Vaccum Bag - 14x20', 67.06, 9);
insert into product (name, unit_price, category_id) values ('Soup Campbells Split Pea And Ham', 150.17, 17);
insert into product (name, unit_price, category_id) values ('Cookies - Fortune', 129.8, 6);
insert into product (name, unit_price, category_id) values ('Carbonated Water - Peach', 52.36, 11);
insert into product (name, unit_price, category_id) values ('Veal - Inside Round / Top, Lean', 133.22, 5);
insert into product (name, unit_price, category_id) values ('Magnotta Bel Paese Red', 167.05, 3);
insert into product (name, unit_price, category_id) values ('Potatoes - Instant, Mashed', 130.11, 16);
insert into product (name, unit_price, category_id) values ('Ecolab - Orange Frc, Cleaner', 41.89, 11);
insert into product (name, unit_price, category_id) values ('Drambuie', 32.41, 3);
insert into product (name, unit_price, category_id) values ('Lettuce - California Mix', 84.53, 7);
insert into product (name, unit_price, category_id) values ('Flour - Chickpea', 180.28, 11);
insert into product (name, unit_price, category_id) values ('Rosemary - Dry', 171.92, 7);
insert into product (name, unit_price, category_id) values ('Coffee Swiss Choc Almond', 117.29, 9);
insert into product (name, unit_price, category_id) values ('Dip - Tapenade', 45.16, 2);
insert into product (name, unit_price, category_id) values ('Scallops 60/80 Iqf', 89.38, 14);
insert into product (name, unit_price, category_id) values ('Fish - Halibut, Cold Smoked', 133.97, 17);
insert into product (name, unit_price, category_id) values ('Wine - Red, Concha Y Toro', 48.12, 15);
insert into product (name, unit_price, category_id) values ('Pork - Belly Fresh', 117.21, 20);
insert into product (name, unit_price, category_id) values ('Cakes Assorted', 116.59, 9);
insert into product (name, unit_price, category_id) values ('Cinnamon Rolls', 18.43, 5);
insert into product (name, unit_price, category_id) values ('Tart - Pecan Butter Squares', 179.99, 2);
insert into product (name, unit_price, category_id) values ('Peas Snow', 192.37, 6);
insert into product (name, unit_price, category_id) values ('Snails - Large Canned', 167.32, 9);
insert into product (name, unit_price, category_id) values ('Puree - Strawberry', 33.6, 6);
insert into product (name, unit_price, category_id) values ('Pepper - Red Thai', 30.1, 3);
insert into product (name, unit_price, category_id) values ('Fudge - Chocolate Fudge', 72.48, 8);
insert into product (name, unit_price, category_id) values ('Plate Foam Laminated 9in Blk', 10.42, 14);
insert into product (name, unit_price, category_id) values ('Pepper - Yellow Bell', 107.61, 8);
insert into product (name, unit_price, category_id) values ('Potatoes - Purple, Organic', 156.15, 4);
insert into product (name, unit_price, category_id) values ('Stock - Veal, Brown', 49.2, 3);
insert into product (name, unit_price, category_id) values ('Orange Roughy 4/6 Oz', 151.3, 14);
insert into product (name, unit_price, category_id) values ('Tart Shells - Sweet, 3', 163.79, 5);
insert into product (name, unit_price, category_id) values ('Water - Perrier', 63.55, 5);
insert into product (name, unit_price, category_id) values ('Muffin Mix - Lemon Cranberry', 83.01, 7);
insert into product (name, unit_price, category_id) values ('Spinach - Frozen', 153.51, 20);
insert into product (name, unit_price, category_id) values ('Leeks - Large', 11.14, 12);
insert into product (name, unit_price, category_id) values ('Table Cloth 91x91 Colour', 98.41, 20);
insert into product (name, unit_price, category_id) values ('Appetizer - Mango Chevre', 135.39, 20);
insert into product (name, unit_price, category_id) values ('Chocolate - Compound Coating', 161.32, 10);
insert into product (name, unit_price, category_id) values ('Truffle Cups - White Paper', 74.15, 9);
insert into product (name, unit_price, category_id) values ('Ginger - Pickled', 198.88, 6);
insert into product (name, unit_price, category_id) values ('Soup - Campbells, Lentil', 198.39, 10);
insert into product (name, unit_price, category_id) values ('Miso - Soy Bean Paste', 190.32, 9);
insert into product (name, unit_price, category_id) values ('Salt - Seasoned', 150.17, 11);
insert into product (name, unit_price, category_id) values ('Plasticspoonblack', 100.78, 5);
insert into product (name, unit_price, category_id) values ('Appetizer - Mini Egg Roll, Shrimp', 43.88, 20);
insert into product (name, unit_price, category_id) values ('Urban Zen Drinks', 87.82, 15);
insert into product (name, unit_price, category_id) values ('Food Colouring - Blue', 110.43, 6);
insert into product (name, unit_price, category_id) values ('Cheese - Cambozola', 82.13, 13);
insert into product (name, unit_price, category_id) values ('Nougat - Paste / Cream', 13.81, 6);
insert into product (name, unit_price, category_id) values ('Coffee - Irish Cream', 50.42, 17);
insert into product (name, unit_price, category_id) values ('Dried Cranberries', 78.23, 3);
insert into product (name, unit_price, category_id) values ('Clams - Canned', 64.01, 2);
insert into product (name, unit_price, category_id) values ('Canadian Emmenthal', 30.71, 9);
insert into product (name, unit_price, category_id) values ('Compound - Pear', 66.05, 19);
insert into product (name, unit_price, category_id) values ('Cake - Dulce De Leche', 21.61, 14);
insert into product (name, unit_price, category_id) values ('Beef - Top Butt', 195.28, 4);
insert into product (name, unit_price, category_id) values ('Tarts Assorted', 87.61, 7);
insert into product (name, unit_price, category_id) values ('Taro Root', 64.99, 8);
insert into product (name, unit_price, category_id) values ('Pork - Liver', 155.05, 12);
insert into product (name, unit_price, category_id) values ('Crush - Grape, 355 Ml', 94.48, 15);
insert into product (name, unit_price, category_id) values ('Pepper - Scotch Bonnet', 127.94, 3);
insert into product (name, unit_price, category_id) values ('Juice - Prune', 20.54, 8);
insert into product (name, unit_price, category_id) values ('Longos - Grilled Salmon With Bbq', 24.39, 11);
insert into product (name, unit_price, category_id) values ('Cocoa Powder - Natural', 112.13, 6);
insert into product (name, unit_price, category_id) values ('Veal Inside - Provimi', 36.26, 4);
insert into product (name, unit_price, category_id) values ('Sage Derby', 179.92, 10);
insert into product (name, unit_price, category_id) values ('Muffin - Zero Transfat', 110.07, 13);
insert into product (name, unit_price, category_id) values ('Pasta - Lasagne, Fresh', 122.58, 14);
insert into product (name, unit_price, category_id) values ('Tart Shells - Barquettes, Savory', 79.18, 12);
insert into product (name, unit_price, category_id) values ('Spring Roll Veg Mini', 139.73, 1);
insert into product (name, unit_price, category_id) values ('Sauce - Demi Glace', 134.51, 10);
insert into product (name, unit_price, category_id) values ('Bread - Roll, Whole Wheat', 28.15, 10);
insert into product (name, unit_price, category_id) values ('Soup - Campbells Tomato Ravioli', 162.17, 10);
insert into product (name, unit_price, category_id) values ('Vinegar - Cider', 145.41, 17);
insert into product (name, unit_price, category_id) values ('Crackers - Trio', 192.69, 3);
insert into product (name, unit_price, category_id) values ('Sausage - Blood Pudding', 41.6, 16);
insert into product (name, unit_price, category_id) values ('Sugar - White Packet', 103.22, 16);
insert into product (name, unit_price, category_id) values ('Chocolate - Feathers', 114.32, 3);
insert into product (name, unit_price, category_id) values ('Pie Pecan', 75.46, 13);
insert into product (name, unit_price, category_id) values ('Beef - Cow Feet Split', 31.94, 5);
insert into product (name, unit_price, category_id) values ('Tea - Lemon Green Tea', 165.73, 12);
insert into product (name, unit_price, category_id) values ('Oregano - Fresh', 92.06, 9);
insert into product (name, unit_price, category_id) values ('Wine - Cabernet Sauvignon', 88.49, 6);
insert into product (name, unit_price, category_id) values ('Glass Clear 7 Oz Xl', 43.77, 3);
insert into product (name, unit_price, category_id) values ('Tomatoes', 128.19, 20);
insert into product (name, unit_price, category_id) values ('Tea - Jasmin Green', 123.62, 8);
insert into product (name, unit_price, category_id) values ('Wiberg Super Cure', 13.09, 12);
insert into product (name, unit_price, category_id) values ('Towels - Paper / Kraft', 165.51, 20);
insert into product (name, unit_price, category_id) values ('Carroway Seed', 104.44, 16);
insert into product (name, unit_price, category_id) values ('Sprite - 355 Ml', 137.1, 18);
insert into product (name, unit_price, category_id) values ('Pastry - Apple Muffins - Mini', 164.93, 20);
insert into product (name, unit_price, category_id) values ('Schnappes Peppermint - Walker', 68.8, 15);
insert into product (name, unit_price, category_id) values ('Soup - Knorr, Classic Can. Chili', 58.88, 2);
